# This is a basic workflow to help you get started with Actions

name: UpdateIPTV

on:
#  workflow_dispatch
  schedule:
  - cron: "0,30 * * * *"
    
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  Update:
    runs-on: ubuntu-latest
    steps:    
    - name: Set up Go # 设置Go环境
      uses: actions/setup-go@v1
      with:
        go-version: '^1.19' # 指定所需的Go版本
          
    - name: Checkout
      uses: actions/checkout@v3

    - name: GetTime
      id: date
      run: |
        sudo cp /etc/localtime /etc/localtime.bak
        sudo ln -sf /usr/share/zoneinfo/Asia/Shanghai /etc/localtime
        echo "::set-output name=date::$(date +'%Y-%m-%d %H:%M:%S CST')"

    - name: Update
      run: |
        # 获取直播源
        rm -f Fanmingming.m3u
        wget https://raw.githubusercontent.com/fanmingming/live/main/tv/m3u/ipv6.m3u -O Fanmingming.m3u

        # Group-Title
        rm -f group-title.txt
        awk -F'group-title="' '/tvg-name/ {print $2}' Meroser.m3u | awk -F'",' '{print $1}' | awk '!seen[$0]++' > group-title-f.txt
        awk -F'group-title="' '/tvg-name/ {print $2}' Fanmingming.m3u | awk -F'",' '{print $1}' | awk '!seen[$0]++' > group-title-m.txt

        # Tv-BOX
        awk '/EXTINF/ {printf "%s,", substr($0, index($0, ",") + 1); getline next_line; printf "%s", next_line; print ""}' Fanmingming.m3u > temp.txt
        awk '/EXTINF/ {printf "%s,", substr($0, index($0, ",") + 1); getline next_line; printf "%s", next_line; print ""}' Meroser.m3u >> temp.txt
        sort temp.txt > tvbox.txt
        rm -f temp.txt
        
        # HFPIAO
        rm -f hfpiao.m3u && touch hfpiao.m3u
        sed -i '/CCTV-[1-9][0-9+]\? /,+1d' hfpiao.m3u
        sed -n -e '/group-title="/,+1p' Meroser.m3u > HFPIAO01.m3u
        #sed -n -e '/group-title="/,+1p' Fanmingming.m3u > HFPIAO02.m3u
        cat HFPIAO01.m3u >> hfpiao.m3u
        #cat HFPIAO02.m3u >> hfpiao.m3u
        rm -f HFPIAO01.m3u
        #rm -f HFPIAO02.m3u
        sed -i '1i #EXTM3U' hfpiao.m3u
        sed -i '/^\s*$/d' hfpiao.m3u

        # 节目源
        rm -f hfpiao.xml
        rm -f EPG.xml && wget https://epg.112114.xyz/pp.xml -O EPG.xml
        awk -F'tvg-id="' '/tvg-name/ {print $2}' hfpiao.m3u | awk -F'"' '/tvg-name=/ {print $2}' hfpiao.m3u >> channel_list.log
        go mod download
        go run main.go
        rm -f channel_list.log
        echo "Auto Update IPTV in ${{ steps.date.outputs.date }} 修改自Moexin/IPTV" > README.md

    - name: Clean
      run: |
        git config --local user.email "github-actions[bot]@users.noreply.github.com"
        git config --local user.name "github-actions[bot]"
        git checkout --orphan latest_branch
        git add -A
        git commit -am "${{ steps.date.outputs.date }}"
        git branch -D main
        git branch -m main

    - name: Push
      run: git push -f origin main
